name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    # force all `run:` steps to use Bash, even on Windows
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    # MSYS2 on Windows for Autotools + make + gcc
    - name: Setup MSYS2 (Windows only)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel

    # Install Autotools on Linux/macOS
    - name: Install build deps (Linux/macOS)
      run: |
        case "$(uname -s)" in
          Linux*)
            sudo apt-get update
            sudo apt-get install -y autoconf automake libtool pkg-config build-essential
            ;;
          Darwin*)
            brew update
            brew install autoconf automake libtool pkg-config
            ;;
          *)
            # Windows under MSYS2 has base-devel already
            ;;
        esac

    # Build & test on all platforms
    - name: Build
      run: |
        CORES=$(nproc 2>/dev/null || sysctl -n hw.ncpu)
        make -j"$CORES"
        
