name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper versioning
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install sphinx sphinx-rtd-theme breathe
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
    
    - name: Build documentation
      run: |
        cd docs
        make all
    
    - name: Upload docs artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/build/html

  deploy-docs:
    if: github.event_name != 'pull_request'
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2 