name: Documentation Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'include/**'
      - 'src/**'
      - 'pybind/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build documentation
        run: |
          cd docs
          chmod +x build_docs.sh
          ./build_docs.sh
          
      - name: Deploy to GitHub Wiki
        id: wiki-publish
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs/build/html"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      # Alternative approach if the SwiftDocOrg action doesn't work well
      - name: Deploy to GitHub Wiki (Fallback)
        if: failure() && steps.wiki-publish.outcome == 'failure'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone "https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.wiki.git" wiki
          cp -r docs/build/html/* wiki/
          cd wiki
          git add .
          git commit -m "Update documentation" || echo "No changes to commit"
          git push 